### PR TITLE
Working

### PR DESCRIPTION
**Pull request by nanofuxion**
1. Removed dependency on native module sharp allowing for use in containers such as glitch.com
2. Fixed crash caused by groups not providing username ".text" in iqHandler.js
3. Added the ability to load images directly from URLs in the process of removing dependency on sharp.
4. Added kik version changer, review config.js to see exact versions
5. Added support for sending and receiving stickers.
6. Added support for sending and receiving system messages.
7. Added support for sending and receiving videos(gifs)
8. Fixed 2 packet limitation in kikConnection.js

### CODE REVIEW

**Comment by nanofuxion** [comment]
Approved!

**Comment by nanofuxion** [comment]
sorry thought this was going to my fork,
I have made some changes that hinder performance in favor of compatibility.

**Comment by YassienW** [comment]
This is quite an impressive amount of work! Would you be interested in merging it to this project?

**Comment by nanofuxion** [comment]
As long as you don't mind the transition from from sharp or the the transition is kind of embedded into the video supports as well, or if you do, doing a bit of work to reinstate sharp.

**Comment by YassienW** [comment]
Well, i found sharp to be necessary for image sending to work properly. The images have to be converted before uploading. I would surely be interested in merging at least the new requests. Can you join #kiknodeapi group on kik so we can have a chat about the changes?

**Comment by nanofuxion** [comment]
sure

**Comment by nanofuxion** [comment]
Will revisit upon further improvements.

**Pull request closed without merging**
